import { ArrowRight, BadgeCheck, BriefcaseBusiness, CheckCircle2, FileCheck2, Landmark, Menu, MessageCircle, ShieldCheck, Users } from 'lucide-react';
import { CookieConsent } from '@/components/cookie-consent';

const whatsappUrl = 'https://wa.me/558287140225?text=Ol%C3%A1%2C%20gostaria%20de%20falar%20com%20a%20equipe%20da%20Ricardo%20Fonseca%20Advocacia.';
const services = [
  { icon: FileCheck2, title: 'Benefícios do INSS', text: 'Orientação em requerimentos, revisões e análise de benefícios previdenciários.' },
  { icon: Landmark, title: 'Aposentadorias', text: 'Análise do histórico contributivo e planejamento do pedido administrativo.' },
  { icon: ShieldCheck, title: 'Benefícios por incapacidade', text: 'Acompanhamento em pedidos relacionados à incapacidade temporária ou permanente.' },
  { icon: Users, title: 'BPC / LOAS', text: 'Avaliação dos requisitos e suporte na organização documental do benefício assistencial.' },
];
const team = [
  { initials: 'RF', name: 'Ricardo Fonseca', role: 'Advogado', text: 'Responsável pela condução jurídica, análise estratégica, definição das teses, medidas judiciais e acompanhamento dos processos.' },
  { initials: 'JF', name: 'Josina Ferreira', role: 'Administrativo e Análise Processual', text: 'Realiza o pré-atendimento, triagem inicial, organização documental, análise processual e suporte administrativo.' },
  { initials: 'MP', name: 'Márcio Pontes', role: 'Logística e Acompanhamento Externo', text: 'Acompanha clientes junto ao INSS, bancos e demais órgãos, além da logística de exames, perícias e documentos.' },
  { initials: 'YS', name: 'Yasmine Silvério', role: 'Cadastro e Requerimentos Administrativos', text: 'Cuida do cadastro, organização inicial dos documentos, contratos e requerimentos administrativos perante o INSS.' },
];

export default function Home() {
  const structuredData = { '@context': 'https://schema.org', '@type': 'LegalService', name: 'Ricardo Fonseca Advocacia', description: 'Escritório com foco em Direito Previdenciário.', telephone: '+55 82 8714-0225', postalCode: '57030-101', areaServed: 'Maceió, Alagoas', taxID: '54.145.344/0001-18', url: 'https://ricardo-fonseca-advocaciaa.vercel.app' };
  return <>
    <a href="#conteudo" className="skip-link">Pular para o conteúdo</a>
    <header className="site-header"><div className="container nav-wrap"><a className="brand" href="#inicio" aria-label="Ricardo Fonseca Advocacia e Consultoria — início"><img src="/logo-navy-cropped.png" alt="Ricardo Fonseca — Advocacia e Consultoria"/></a><nav className="desktop-nav" aria-label="Navegação principal"><a href="#atuacao">Atuação</a><a href="#escritorio">O escritório</a><a href="#equipe">Equipe</a><a href="#duvidas">Dúvidas</a></nav><a className="button button-small desktop-cta" href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Falar no WhatsApp</a><details className="mobile-menu"><summary aria-label="Abrir menu"><Menu size={23}/></summary><nav><a href="#atuacao">Atuação</a><a href="#escritorio">O escritório</a><a href="#equipe">Equipe</a><a href="#duvidas">Dúvidas</a></nav></details></div></header>
    <main id="conteudo">
      <section className="hero" id="inicio"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span/> Direito Previdenciário</p><h1>Seu direito previdenciário tratado com <em>atenção e clareza.</em></h1><p className="hero-text">Atendimento próximo e atuação técnica em demandas perante o INSS, desde a análise inicial até as medidas administrativas e judiciais cabíveis.</p><div className="hero-actions"><a className="button" href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle size={19}/> Conversar com a equipe</a><a className="text-link" href="#atuacao">Conheça nossa atuação <ArrowRight size={17}/></a></div><ul className="trust-list"><li><CheckCircle2/> Análise individualizada</li><li><CheckCircle2/> Acompanhamento próximo</li><li><CheckCircle2/> Informação transparente</li></ul></div><aside className="hero-card"><div className="card-kicker"><BadgeCheck size={18}/> Atendimento organizado</div><h2>Do primeiro contato ao acompanhamento do seu caso.</h2><ol><li><span>01</span><div><strong>Escuta e triagem</strong><p>Entendemos sua situação e identificamos os documentos necessários.</p></div></li><li><span>02</span><div><strong>Análise técnica</strong><p>A equipe organiza as informações para avaliação jurídica.</p></div></li><li><span>03</span><div><strong>Orientação e acompanhamento</strong><p>Explicamos os caminhos possíveis e acompanhamos cada etapa.</p></div></li></ol><p className="disclaimer">Cada caso possui características próprias. A análise não representa garantia de resultado.</p></aside></div></section>
      <section className="section" id="atuacao"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span/> Áreas de atuação</p><h2>Orientação previdenciária para diferentes momentos.</h2></div><p>Atuação responsável na análise e condução de demandas administrativas e judiciais relacionadas à Previdência Social.</p></div><div className="service-grid">{services.map(({icon:Icon,title,text})=><article className="service-card" key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="section soft-section" id="escritorio"><div className="container about-grid"><div className="about-visual"><img src="/monogram-navy-cropped.png" alt=""/><span>Atuação técnica<br/>e humanizada</span></div><div><p className="eyebrow"><span/> O escritório</p><h2>Proximidade, organização e segurança em cada etapa.</h2><p>Na Ricardo Fonseca Advocacia, cada atendimento começa pela escuta. Nossa equipe trabalha de forma integrada para que documentos, requerimentos e medidas jurídicas sejam conduzidos com organização e atenção aos detalhes.</p><div className="values"><div><BriefcaseBusiness/><strong>Atuação técnica</strong><span>Análise cuidadosa de cada demanda.</span></div><div><Users/><strong>Trabalho integrado</strong><span>Equipe alinhada durante todo o atendimento.</span></div></div></div></div></section>
      <section className="section" id="equipe"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span/> Conheça nossa equipe</p><h2>Pessoas preparadas para acompanhar você.</h2></div><p>Funções bem definidas e atuação conjunta, do primeiro atendimento à conclusão do processo.</p></div><div className="team-grid">{team.map(p=><article className="team-card" key={p.name}><div className="avatar">{p.initials}</div><div><h3>{p.name}</h3><p className="role">{p.role}</p><p>{p.text}</p></div></article>)}</div></div></section>
      <section className="section faq-section" id="duvidas"><div className="container faq-grid"><div><p className="eyebrow light"><span/> Dúvidas frequentes</p><h2>Informação clara para o primeiro passo.</h2><p>As respostas são gerais. A orientação adequada depende da análise individual de cada situação.</p></div><div className="faq-list"><details><summary>Quais documentos devo enviar no primeiro contato?</summary><p>Em geral, identificação, comprovante de residência e documentos do benefício ou histórico contributivo. A equipe indicará o necessário.</p></details><details><summary>O atendimento pode começar pelo WhatsApp?</summary><p>Sim. O canal permite o pré-atendimento e a triagem inicial. Informações sensíveis serão solicitadas apenas quando necessárias.</p></details><details><summary>O escritório acompanha requerimentos no INSS?</summary><p>Sim. A atuação inclui requerimentos administrativos e, quando juridicamente cabível, análise de medidas judiciais.</p></details></div></div></section>
      <section className="contact-section" id="contato"><div className="container contact-box"><div><p className="eyebrow"><span/> Entre em contato</p><h2>Conte sua situação para nossa equipe.</h2><p>Inicie o pré-atendimento pelo WhatsApp. Retornaremos com as orientações para a triagem.</p></div><a className="button" href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle size={20}/> Iniciar atendimento</a></div></section>
    </main>
    <footer><div className="container footer-grid"><div className="brand footer-brand"><img src="/logo-silver-cropped.png" alt="Ricardo Fonseca — Advocacia e Consultoria"/></div><div><strong>Contato</strong><a href={whatsappUrl}>+55 82 8714-0225</a><span>CEP 57030-101 · Maceió/AL</span></div><div><strong>Informações legais</strong><span>CNPJ 54.145.344/0001-18</span><a href="#privacidade">Política de Privacidade</a></div></div><div className="container footer-bottom"><span>© 2026 Ricardo Fonseca Advocacia.</span><span>Conteúdo informativo. Não constitui promessa de resultado.</span></div></footer>
    <a className="floating-whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Falar pelo WhatsApp"><MessageCircle/></a><CookieConsent/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/>
  </>;
}
